# ============================================================================
# ShivX Docker Compose - Production Secrets Configuration
# ============================================================================
# This file defines Docker secrets for production deployment
# Secrets are stored securely and mounted as files in containers
# ============================================================================

version: '3.8'

services:
  # ==========================================================================
  # ShivX Application - Override with secrets
  # ==========================================================================
  shivx:
    environment:
      # Database connection with secrets
      - SHIVX_DATABASE_URL=postgresql://shivx:${POSTGRES_PASSWORD}@postgres:5432/shivx
      # Load secrets from Docker secrets
      - SHIVX_SECRET_KEY_FILE=/run/secrets/shivx_secret_key
      - SHIVX_JWT_SECRET_FILE=/run/secrets/jwt_secret
      - SHIVX_API_KEY_FILE=/run/secrets/api_key
    secrets:
      - shivx_secret_key
      - jwt_secret
      - api_key
      - db_password

  # ==========================================================================
  # PostgreSQL - Use secrets for password
  # ==========================================================================
  postgres:
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_password

  # ==========================================================================
  # Grafana - Use secrets for admin password
  # ==========================================================================
  grafana:
    environment:
      GF_SECURITY_ADMIN_PASSWORD__FILE: /run/secrets/grafana_admin_password
    secrets:
      - grafana_admin_password

# ==========================================================================
# Docker Secrets Definitions
# ==========================================================================
secrets:
  # Application secrets
  shivx_secret_key:
    file: ./secrets/shivx_secret_key.txt

  jwt_secret:
    file: ./secrets/jwt_secret.txt

  api_key:
    file: ./secrets/api_key.txt

  # Database password
  db_password:
    file: ./secrets/db_password.txt

  # Grafana admin password
  grafana_admin_password:
    file: ./secrets/grafana_admin_password.txt

  # PostgreSQL SSL certificates
  postgres_server_cert:
    file: ./secrets/postgres/server.crt

  postgres_server_key:
    file: ./secrets/postgres/server.key

  postgres_ca_cert:
    file: ./secrets/postgres/ca.crt

# ==========================================================================
# USAGE INSTRUCTIONS
# ==========================================================================
# 1. Create secrets directory: mkdir -p deploy/secrets
# 2. Generate secrets (see scripts/generate_secrets.sh)
# 3. Deploy with: docker-compose -f docker-compose.yml -f docker-compose.secrets.yml up -d
# 4. For production: Use Docker Swarm secrets or external secret manager
# ==========================================================================
