# Prometheus Configuration for ShivX
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'shivx-production'
    environment: 'production'

# Alerting configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Rule files
rule_files:
  - '/etc/prometheus/alerting-rules.yml'

# Scrape configurations
scrape_configs:
  # ShivX application metrics
  - job_name: 'shivx'
    static_configs:
      - targets: ['shivx:9090']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # PostgreSQL exporter (if deployed)
  - job_name: 'postgres'
    static_configs:
      - targets: []
        # - postgres-exporter:9187

  # Redis exporter (if deployed)
  - job_name: 'redis'
    static_configs:
      - targets: []
        # - redis-exporter:9121
