# ============================================================================
# ShivX Production Secrets - Example Template
# ============================================================================
# DO NOT commit actual secrets to version control!
# This is a template showing the structure of secrets needed
# ============================================================================

# Copy this file and populate with actual values:
# cp secrets.example.yml secrets.yml
# chmod 600 secrets.yml  # Restrict permissions

# ============================================================================
# Application Secrets
# ============================================================================

# Secret key for encryption (32+ bytes, URL-safe base64)
# Generate: python -c "import secrets; print(secrets.token_urlsafe(32))"
shivx_secret_key: "REPLACE_WITH_RANDOM_SECRET_KEY_MINIMUM_32_BYTES"

# JWT secret for authentication tokens (32+ bytes)
# Generate: python -c "import secrets; print(secrets.token_urlsafe(32))"
jwt_secret: "REPLACE_WITH_RANDOM_JWT_SECRET_MINIMUM_32_BYTES"

# API key for external service authentication
# Generate: python -c "import secrets; print(secrets.token_urlsafe(32))"
api_key: "REPLACE_WITH_RANDOM_API_KEY"

# ============================================================================
# Database Secrets
# ============================================================================

# PostgreSQL password for 'shivx' user
# Generate: python -c "import secrets; print(secrets.token_urlsafe(24))"
db_password: "REPLACE_WITH_STRONG_DB_PASSWORD"

# PostgreSQL replication password (if using replication)
db_replication_password: "REPLACE_WITH_REPLICATION_PASSWORD"

# ============================================================================
# Monitoring Secrets
# ============================================================================

# Grafana admin password
# Must be strong for production access
grafana_admin_password: "REPLACE_WITH_STRONG_GRAFANA_PASSWORD"

# Prometheus basic auth password (if enabled)
prometheus_password: "REPLACE_WITH_PROMETHEUS_PASSWORD"

# ============================================================================
# External Service API Keys
# ============================================================================

# Slack webhook URL for alerts
slack_webhook_url: "https://hooks.slack.com/services/YOUR/WEBHOOK/URL"

# PagerDuty integration key for critical alerts
pagerduty_integration_key: "YOUR_PAGERDUTY_INTEGRATION_KEY"

# Sentry DSN for error tracking
sentry_dsn: "https://YOUR_SENTRY_DSN@sentry.io/PROJECT_ID"

# OpenAI API key (if using LLM features)
openai_api_key: "sk-REPLACE_WITH_OPENAI_KEY"

# ============================================================================
# Trading Wallet Secrets
# ============================================================================

# Solana wallet private key (base58 encoded)
# CRITICAL: Use testnet wallet for paper trading!
# NEVER commit mainnet wallets with real funds!
solana_wallet_private_key: "REPLACE_WITH_TESTNET_WALLET_PRIVATE_KEY"

# Wallet seed phrase (encrypted backup)
# NEVER store unencrypted seed phrases!
wallet_seed_phrase_encrypted: "ENCRYPTED_SEED_PHRASE"

# ============================================================================
# Cloud Provider Credentials
# ============================================================================

# AWS credentials for S3, ECS, etc.
aws_access_key_id: "REPLACE_WITH_AWS_ACCESS_KEY"
aws_secret_access_key: "REPLACE_WITH_AWS_SECRET_KEY"

# ============================================================================
# SSL/TLS Certificate Passphrases
# ============================================================================

# Private key passphrase (if encrypted)
ssl_key_passphrase: "REPLACE_WITH_SSL_KEY_PASSPHRASE"

# ============================================================================
# SECURITY CHECKLIST
# ============================================================================
# Before deploying to production, verify:
#
# [ ] All REPLACE_WITH_* placeholders have been filled with actual values
# [ ] All secrets are at least 32 bytes (256 bits) for cryptographic keys
# [ ] Passwords follow organization's password policy
# [ ] No secrets are committed to version control
# [ ] Secrets file has restricted permissions (chmod 600)
# [ ] Secrets are backed up in a secure location (e.g., AWS Secrets Manager)
# [ ] Secrets rotation policy is documented and scheduled
# [ ] Access to secrets is logged and monitored
# [ ] Testnet wallets are used for paper trading mode
# [ ] Production secrets differ from staging/development
#
# ============================================================================
